---
- hosts: cumulus
  tasks:

  - name: "Initialize empty dictionary of runtime lldp neighbors"
    set_fact:
       runtime_lldp_neighbors: []

  - name: "Initialize empty dictionary of configured lldp neighbors"
    set_fact:
       configured_lldp_neighbors: []

  - name: "Get lldp neighbors"
    nclu:
      commands:
        - show lldp json
    register: lldp_json
    when: "'cumulus' in group_names"

  - name: "Save output for further analysis"
    set_fact: result="{{ lldp_json.msg }}"



#  - name: "verify output"
#    debug: msg="{{result}}"

### append runtime neighbor to list when it matches configured neighbor
  - name: "Form list of existing lldp neighbors, which match configured neighbors"
    set_fact:
       runtime_lldp_neighbors: "{{ runtime_lldp_neighbors +  [ lldp_neighbors[item.name] ] }}"
### loop through output "interfaces" array, select "name" value from each interface, which is actual neighbor name
    loop: "{{ result | json_query('lldp[0].interface[*]') }}"
    when: (lldp_neighbors[item.name] is defined and lldp_neighbors[item.name] == item.chassis[0].name[0].value) 
    loop_control:
       label: "{{ item.name }}"

  - name: "Form list of configured lldp neighbors"
    set_fact:
       configured_lldp_neighbors: "{{ configured_lldp_neighbors + [item.value]}}"
    with_dict: "{{ lldp_neighbors }}"

  - name: "Identify difference between runtime and configured neighbors"
    set_fact:
       diff_lldp_neighbors: "{{ configured_lldp_neighbors | symmetric_difference(runtime_lldp_neighbors) }}"

  - name: Analyze and print result
    debug: 
       msg: "{{ 'Topology is correct' if (diff_lldp_neighbors | length) == 0 else diff_lldp_neighbors}}"
