---
- hosts: all
  gather_facts: no
  serial: 2
  vars:
    time_inconsistency: []
    ntp_server_active: 'no'

  tasks:

  - include_tasks: tasks/cumulus-get-time-info.yml 
    when: "'cumulus' in group_names" 

  - include_tasks: tasks/exos-get-time-info.yml 
    when: "'exos' in group_names" 

  - include_tasks: tasks/linux-get-time-info.yml 
    when: "'kvm' in group_names" 

  - include_tasks: tasks/utm-get-time-info.yml 
    when: "'utm' in group_names" 

### Find inconsistencies 

  - name: "Compare local and host time"
    set_fact:
       time_inconsistency: "{{ time_inconsistency + [ inventory_hostname + ': Incorrect time. Host reported time is more than 10 seconds different from current time. Host reported time: ' + host_date.stdout]}}"
    when: time_diff | int | abs > 10 

  - name: "Verify timezone"
    set_fact:
       time_inconsistency: "{{ time_inconsistency + [ inventory_hostname + ': Incorrect timezone. Host reported timezone: ' + host_timezone + '. Should be: ' + timezone  ]}}"
    when: host_timezone != timezone 

  - name: "Report ntp server activity"
    set_fact: 
      time_inconsistency: "{{ time_inconsistency + [ inventory_hostname + ': no active ntp servers found']}}"
    when: ntp_server_active == 'no'

  - name: "Check if all ntp servers are present in configuration"
    set_fact: 
      time_inconsistency: "{{ time_inconsistency + [ inventory_hostname + ': ntp server ' + item + ' is missing in host configuration file']}}"
    when: item not in configured_ntp_servers
    loop: "{{ ntp_servers }}"

  - name: Analyze and print result
    debug: 
       msg: "{{ 'Time and ntp configuration is correct' if (time_inconsistency | length) == 0 else time_inconsistency}}"

  - name: Save results to file
    lineinfile:
      line: "{{ inventory_hostname + ': Time and ntp configuration is correct' if (time_inconsistency | length) == 0 else time_inconsistency}}"
      path: "{{playbook_dir}}/logs/time.log"
    delegate_to: localhost
